[package]
name = "test-post"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sparse-merkle-tree = { git = "https://github.com/vibhurajeev/sparse-merkle-tree.git" }
actix-web = "4.3.1"
tokio = "1.30.0"
risc0-zkvm = {version = "0.18.0"}
serde = "1.0"
primitive-types = "0.12.1"
hex = "0.4.3"
serde_json = "1.0.103"
bincode = "1.3.3"
anyhow = "1.0.75"
